### PR TITLE
SCMOD 7628: Log4j update

### PR DESCRIPTION
**Pull request by kusumaghoshdastidar**
Jira: https://portal.digitalsafe.net/browse/SCMOD-7628

Dev builds: http://sou-jenkins2.hpeswlab.net/job/CAFAudit/view/Developer/job/CAFAudit~audit-service~SCMOD-7628~CI/

### CODE REVIEW

**Review by dermot-hardy — COMMENTED** [review]
What is wrong with using the BOM?  If you're moving away from the BOM and to individual dependencies then they should be in their correct place alphabetically in dependency management.

**Review by dermot-hardy — APPROVED** [review]
What is the issue with using the BOM?

**Comment by kusumaghoshdastidar** [comment]
> What is wrong with using the BOM? If you're moving away from the BOM and to individual dependencies then they should be in their correct place alphabetically in dependency management.

The version (2.11.2) the BOM refers to is overridden by a lower version (2.8.2) from com.github.cafapi:caf-common.

**Comment by dermot-hardy** [comment]
That just means that the BOM should be ordered first, before the `caf-common` BOM, so that it takes priority.

**Pull request merged**
