### PR TITLE
CAF-2274: Audit web service changes

### PR DESCRIPTION
**Pull request by mulhollandc**
https://jira.autonomy.com/browse/CAF-2274

### CODE REVIEW

**Comment by mulhollandc** [comment]
@glucy remaining audit web service changes made. Ready for review.

**Comment by glucy** [comment]
**DO NOT MERGE** Until after the v3.0.0 Release has gone out and develop has been 'reset'.

**Comment by glucy** [comment]
**SAFE to use develop**

**Review by glucy — APPROVED** [review]
@dermot-hardy 
You spotted the initial problem, therefore can I ask if you will take a quick look over Connor's updates.

**Pull request merged**
