### PR TITLE
SCMOD-5063: Resolve dependency issues

### PR DESCRIPTION
**Pull request by thilagasanthosh**
https://autjira.microfocus.com/browse/SCMOD-5063

http://sou-jenkins2.hpeswlab.net/job/CAFAudit/view/Developer/job/CAFAudit~audit-service~SCMOD-5063~CI/

### CODE REVIEW

**Comment by michael-bryson** [comment]
@dermot-hardy Sending this one to you as there is an additional file added to fix a dependency issue and I would like you to take a look.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
The `Dummy.java` file is fine but I'm not happy with all these sortpom plugin induced unnecessary changes.  All I expect to see is most of the project poms is version numbers being removed, but instead they can't be reviewed at all because of the volume of changes.

PR changes need to be focused so that they can be reviewed:
https://github.com/salemove/github-review-helper/blob/master/doc/rules.md#focused

**Comment by thilagasanthosh** [comment]
@dermot-hardy ,
Sortpom plugin changes are reverted now and the branch has recommended changes only. Please review and let me know the comments.

**Review by dermot-hardy — APPROVED** [review]
They look OK but I'd like @michael-bryson to have a look.

**Pull request merged**
